Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m22 = linopy.Model()

# Define variables
x_w = m22.add_variables(lower=0,name="wind")
x_s = m22.add_variables(lower=0,name="solar")
x_g = m22.add_variables(lower=0,name="gas")

# Define constraints
m22.add_constraints(x_w + x_s + x_g == demand_2a, name="energy_balance")

m22.add_constraints(x_g <= gas, name="gas_cap")

m22.add_constraints(x_w <= wind * wind_cf, name="wind_cf")
m22.add_constraints(x_s <= solar * solar_cf, name="solar_cf")

# Optional:
m22.add_constraints(x_w <= wind, name="wind_cap")
m22.add_constraints(x_s <= solar, name="solar_cap")

# Objective
m22.add_objective(cost_gas*x_g, sense = "min")

# Solve
m22.solve(solver_name="gurobi")

m22.solution

------------------


[31m---------------------------------------------------------------------------[39m
[31mAssertionError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[5][39m[32m, line 24[39m
[32m     21[39m m22.add_objective(cost_gas*x_g, sense = [33m"[39m[33mmin[39m[33m"[39m)
[32m     23[39m [38;5;66;03m# Solve[39;00m
[32m---> [39m[32m24[39m [43mm22[49m[43m.[49m[43msolve[49m[43m([49m[43msolver_name[49m[43m=[49m[33;43m"[39;49m[33;43mgurobi[39;49m[33;43m"[39;49m[43m)[49m
[32m     26[39m m22.solution

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/linopy/model.py:1143[39m, in [36mModel.solve[39m[34m(self, solver_name, io_api, explicit_coordinate_names, problem_fn, solution_fn, log_fn, basis_fn, warmstart_fn, keep_files, env, sanitize_zeros, sanitize_infinities, slice_size, remote, progress, **solver_options)[39m
[32m   1140[39m     solver_name = available_solvers[[32m0[39m]
[32m   1142[39m logger.info([33mf[39m[33m"[39m[33m Solve problem using [39m[38;5;132;01m{[39;00msolver_name.title()[38;5;132;01m}[39;00m[33m solver[39m[33m"[39m)
[32m-> [39m[32m1143[39m [38;5;28;01massert[39;00m solver_name [38;5;129;01min[39;00m available_solvers, [33mf[39m[33m"[39m[33mSolver [39m[38;5;132;01m{[39;00msolver_name[38;5;132;01m}[39;00m[33m not installed[39m[33m"[39m
[32m   1145[39m [38;5;66;03m# reset result[39;00m
[32m   1146[39m [38;5;28mself[39m.reset_solution()

[31mAssertionError[39m: Solver gurobi not installed

