Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
network.optimize(solver_name='gurobi')
------------------

----- stderr -----
WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['electricity bus'], dtype='object', name='Bus')
----- stderr -----
INFO:linopy.model: Solve problem using Gurobi solver
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[9], line 1[0m
[0;32m----> 1[0m [43mnetwork[49m[38;5;241;43m.[39;49m[43moptimize[49m[43m([49m[43msolver_name[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mgurobi[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pypsa/optimization/optimize.py:634[0m, in [0;36mOptimizationAccessor.__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    632[0m [38;5;129m@wraps[39m(optimize)
[1;32m    633[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs: Any, [38;5;241m*[39m[38;5;241m*[39mkwargs: Any) [38;5;241m-[39m[38;5;241m>[39m Any:
[0;32m--> 634[0m     [38;5;28;01mreturn[39;00m [43moptimize[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mn[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pypsa/optimization/optimize.py:606[0m, in [0;36moptimize[0;34m(n, snapshots, multi_investment_periods, transmission_losses, linearized_unit_commitment, model_kwargs, extra_functionality, assign_all_duals, solver_name, solver_options, compute_infeasibilities, **kwargs)[0m
[1;32m    604[0m [38;5;28;01mif[39;00m extra_functionality:
[1;32m    605[0m     extra_functionality(n, sns)
[0;32m--> 606[0m status, condition [38;5;241m=[39m [43mm[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43msolver_name[49m[38;5;241;43m=[39;49m[43msolver_name[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43msolver_options[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    608[0m [38;5;28;01mif[39;00m status [38;5;241m==[39m [38;5;124m"[39m[38;5;124mok[39m[38;5;124m"[39m:
[1;32m    609[0m     assign_solution(n)

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/linopy/model.py:1143[0m, in [0;36mModel.solve[0;34m(self, solver_name, io_api, explicit_coordinate_names, problem_fn, solution_fn, log_fn, basis_fn, warmstart_fn, keep_files, env, sanitize_zeros, sanitize_infinities, slice_size, remote, progress, **solver_options)[0m
[1;32m   1140[0m     solver_name [38;5;241m=[39m available_solvers[[38;5;241m0[39m]
[1;32m   1142[0m logger[38;5;241m.[39minfo([38;5;124mf[39m[38;5;124m"[39m[38;5;124m Solve problem using [39m[38;5;132;01m{[39;00msolver_name[38;5;241m.[39mtitle()[38;5;132;01m}[39;00m[38;5;124m solver[39m[38;5;124m"[39m)
[0;32m-> 1143[0m [38;5;28;01massert[39;00m solver_name [38;5;129;01min[39;00m available_solvers, [38;5;124mf[39m[38;5;124m"[39m[38;5;124mSolver [39m[38;5;132;01m{[39;00msolver_name[38;5;132;01m}[39;00m[38;5;124m not installed[39m[38;5;124m"[39m
[1;32m   1145[0m [38;5;66;03m# reset result[39;00m
[1;32m   1146[0m [38;5;28mself[39m[38;5;241m.[39mreset_solution()

[0;31mAssertionError[0m: Solver gurobi not installed

